version: '3.8'

services:
  # TODO: 초기 개발의 편의성을 위해 보안 설정(SSL, 로그인)을 끄고 실행하는 설정
  # 1. Elasticsearch 컨테이너 설정
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node # 클러스터가 아닌 단일 노드로 실행
      - bootstrap.memory_lock=true # 메모리 스왑 방지
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # 메모리 사용량 제한 (로컬 부하 방지)
      - xpack.security.enabled=false # 개발용: 보안(로그인/HTTPS) 비활성화
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data # 데이터를 로컬에 영구 저장
    ports:
      - "9200:9200" # 외부 통신 포트
    networks:
      - elastic

  # 2. Kibana 컨테이너 설정 (데이터 시각화 도구)
  # Elasticsearch에 저장된 데이터를 눈으로 보고 검색 쿼리를 테스트해볼 수 있는 웹 사이트
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200 # Elasticsearch와 연결
    networks:
      - elastic
    depends_on:
      - es01 # Elasticsearch가 먼저 켜져야 함

  #  3. Redis 컨테이너 설정 
  redis:
    image: redis:7-alpine # 가볍고 안정적인 Alpine 리눅스 기반 Redis 이미지
    container_name: redis
    ports:
      - "6379:6379" # 외부:내부 포트 연결 (Spring Boot에서 6379로 접속)
    volumes:
      - redis_data:/data # Redis 데이터를 로컬에 영구 저장 (재시작해도 데이터 유지)
    networks:
      - elastic # 같은 네트워크 그룹에 포함

volumes:
  es_data:
    driver: local
  redis_data:
    driver: local

networks:
  elastic:
    driver: bridge
